openapi: 3.0.3
info:
  title: Agile HRM System
  description: |-
    Insert description here
  version: '1.0.0'
tags:
  - name: Unemployment
    description: Access unemployment statistics
  - name: Demand
    description: Access and set demand targets by occupation
  - name: Employment
    description: Access employment statistics by occupation
  - name: JobPosting
    description: Access a list of available jobs by occupation
  - name: Occupation
    description: Access information about occupations or groups of occupations
  - name: News
    description: Access news related to an occupation
  - name: LearningMaterial
    description: Access learning material for an occupation
  - name: Contentful
    description: Listener for Contentful webhooks
  - name: User
    description: Access and manage user profiles
  - name: Certification
    description: Access certifications
  - name: Analytics
    description: Access reports and publish clickstream analytics
paths:
  /analytics: {}
  /certifications: {}
  /demand:
    get:
      summary: Get demand for a given SOC code
      description: '![sequence diagram](/diagrams/DemandController-getDemand-sequence.svg)'
      operationId: getDemand
      security:
        - auth0: []
      tags:
        - Demand
      parameters:
        - name: query
          in: query
          description: Filters for demand
          schema:
            $ref: '#/components/schemas/DemandQuery'
      responses:
        200:
          description: Demand response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Demand'
  /employment: {}
  /jobs: {}
  /learning: {}
  /news: {}
  /occupations: {}
  /profile: {}
  /unemployment: {}
components:
  schemas:
    SocCode:
      type: string
    LocalDateTime:
      type: string
      format: datetime
    AnalyticsQuery:
      type: object
      properties:
        start:
          $ref: '#/components/schemas/LocalDateTime'
        end:
          $ref: '#/components/schemas/LocalDateTime'
        socCode:
          $ref: '#/components/schemas/SocCode'
    Certification:
      type: object
      properties:
        id:
          type: string
        socCode:
          $ref: '#/components/schemas/SocCode'
        title:
          type: string
        description:
          type: string
        organization:
          type: string
        links:
          type: array
          items:
            $ref: '#/components/schemas/ExternalLink'
    Chart:
      type: object
      properties:
        title:
          type: string
        type:
          type: string
      oneOf:
        - $ref: '#/components/schemas/LineChart'
        - $ref: '#/components/schemas/PieChart'
        - $ref: '#/components/schemas/MapChart'
      discriminator:
        propertyName: type
    ClickData:
      type: object
      properties:
        timestamp:
          type: integer
          format: int64
        elementId:
          type: string
        elementType:
          type: string
        userId:
          type: string
        userPostalCode:
          type: string
        userCurrentOccupation:
          type: string
        userGoalOccupation:
          type: string
    Demand:
      type: object
      properties:
        socCode:
          $ref: '#/components/schemas/SocCode'
        value:
          type: integer
          format: int64
    DemandQuery:
      type: object
      properties:
        socCode:
          $ref: '#/components/schemas/SocCode'
    CertificationResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Certification'
    Employment:
      type: object
      properties:
        id:
          type: integer
          format: int64
        socCode:
          $ref: '#/components/schemas/SocCode'
        date:
          $ref: '#/components/schemas/LocalDateTime'
        value:
          type: integer
          format: int64
        forecasted:
          type: boolean
    EmploymentResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Employment'
    ExternalLink:
      type: object
      properties:
        url:
          type: string
        label:
          type: string
    JobPosting:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        company:
          type: string
        salaryRange:
          type: string
        location:
          type: string
        deadline:
          type: string
        link:
          $ref: '#/components/schemas/ExternalLink'
        source:
          $ref: '#/components/schemas/JobSource'
    JobPostingQuery:
      type: object
      properties:
        socCode:
          $ref: '#/components/schemas/SocCode'
        userQuery:
          type: string
        yearlySalaryUpper:
          type: integer
          format: int64
        yearlySalaryLower:
          type: integer
          format: int64
    JobPostingResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/JobPostingQuery'
    JobSource:
      type: string
      enum: [USA_JOBS]
    LearningContentType:
      type: string
      enum: [VIDEO, COURSE, READING]
    LearningMaterial:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        socCode:
          $ref: '#/components/schemas/SocCode'
        organization:
          type: string
        contentType:
          $ref: '#/components/schemas/LearningContentType'
        links:
          type: array
          items:
            $ref: '#/components/schemas/ExternalLink'
    LearningMaterialQuery:
      type: object
      properties:
        socCode:
          $ref: '#/components/schemas/SocCode'
        contentType:
          $ref: '#/components/schemas/LearningContentType'
    LineChart:
      type: object
      properties:
        x:
          type: array
          items:
            type: number
        y:
          type: array
          items:
            type: number
    MapChart:
      type: object
    News:
      type: object
      properties:
        id:
          type: string
        socCode:
          $ref: '#/components/schemas/SocCode'
        title:
          type: string
        source:
          type: string
        published:
          $ref: '#/components/schemas/LocalDateTime'
        link:
          $ref: '#/components/schemas/ExternalLink'
    NewsQuery:
      type: object
      properties:
        socCode:
          $ref: '#/components/schemas/SocCode'
        source:
          type: string
        after:
          $ref: '#/components/schemas/LocalDateTime'
        before:
          $ref: '#/components/schemas/LocalDateTime'
    NewsResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/News'
    Occupation:
      type: object
      properties:
        socCode:
          $ref: '#/components/schemas/SocCode'
        title:
          type: string
        description:
          type: string
    OccupationResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Occupation'
    PieChart:
      type: object
    Profile:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        email:
          type: string
        postalCode:
          type: string
        currentSocCode:
          $ref: '#/components/schemas/SocCode'
        goalSocCode:
          $ref: '#/components/schemas/SocCode'
        termsOfUseConsent:
          type: boolean
    Report:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Chart'

  securitySchemes:
    auth0:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://dev-2rwfim8h3qzkydvj.us.auth0.com/authorize
          tokenUrl: https://dev-2rwfim8h3qzkydvj.us.auth0.com/oauth/token
          scopes: {}